### ISSUE TITLE
Does not produce any output ?

### ISSUE THREAD

**Issue by bakman2** [halkeye/node-red-contrib-plex#2]
Is plexpass required ? I don't get any data back from the node.

**Comment by halkeye** [comment]
I'm honestly not sure I ever did anything with this. And apparently I wasn't watching it so didn't get notification of issues.

**Comment by halkeye** [comment]
I'm guessing its a fork of https://www.npmjs.com/package/node-red-contrib-plex but I didn't actually fork it, maybe because I couldn't find the original source?

**Comment by bakman2** [comment]
no worries, got it working with https://github.com/scraton/node-red-contrib-plex-ws
