### ISSUE TITLE
Cover image

### ISSUE THREAD

**Issue by dhanzseros** [halkeye/node-red-contrib-plex#3]
Hey halkeye,

Is it possible to push the cover image to Node Red dashboard? I am making a surface to Node Red dashboard who is playing and which movie is playing. It works fine but I cannot figure out how to push the actual playing movie cover to dash. Is it possible with this plugin or I have to make it on other way?

Thank you!
Best,
David

**Comment by halkeye** [comment]
So I'll admit, I don't know where this code came from, and I don't think I wrote it. I only really used node red for like a day, so I don't know the answer to it sorry.

**Comment by halkeye** [comment]
I'm going to close this ticket and archive the repo sorry.
